apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lg1ps0bfo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lg1ps0bfo-nodejs 
  name: lg1ps0bfo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lg1ps0bfo-nodejs 
